/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomSelect {
        "label": string;
        "options": string[];
    }
    interface FieldInput {
        "label": string;
        "name": string;
        "pattern": string;
        "required": boolean;
        "type": string;
        "value": string;
    }
    interface FormInput {
        "label": string;
        "name": string;
        "pattern": string;
        "required": boolean;
        "type": string;
        "value": string;
    }
    interface FormSelect {
        "label": string;
        "options": string[];
        "required": boolean;
        "value": string;
    }
    interface PersonalDetails {
    }
}
export interface FieldInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFieldInputElement;
}
export interface FormInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFormInputElement;
}
export interface FormSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFormSelectElement;
}
declare global {
    interface HTMLCustomSelectElement extends Components.CustomSelect, HTMLStencilElement {
    }
    var HTMLCustomSelectElement: {
        prototype: HTMLCustomSelectElement;
        new (): HTMLCustomSelectElement;
    };
    interface HTMLFieldInputElement extends Components.FieldInput, HTMLStencilElement {
    }
    var HTMLFieldInputElement: {
        prototype: HTMLFieldInputElement;
        new (): HTMLFieldInputElement;
    };
    interface HTMLFormInputElement extends Components.FormInput, HTMLStencilElement {
    }
    var HTMLFormInputElement: {
        prototype: HTMLFormInputElement;
        new (): HTMLFormInputElement;
    };
    interface HTMLFormSelectElement extends Components.FormSelect, HTMLStencilElement {
    }
    var HTMLFormSelectElement: {
        prototype: HTMLFormSelectElement;
        new (): HTMLFormSelectElement;
    };
    interface HTMLPersonalDetailsElement extends Components.PersonalDetails, HTMLStencilElement {
    }
    var HTMLPersonalDetailsElement: {
        prototype: HTMLPersonalDetailsElement;
        new (): HTMLPersonalDetailsElement;
    };
    interface HTMLElementTagNameMap {
        "custom-select": HTMLCustomSelectElement;
        "field-input": HTMLFieldInputElement;
        "form-input": HTMLFormInputElement;
        "form-select": HTMLFormSelectElement;
        "personal-details": HTMLPersonalDetailsElement;
    }
}
declare namespace LocalJSX {
    interface CustomSelect {
        "label"?: string;
        "options"?: string[];
    }
    interface FieldInput {
        "label"?: string;
        "name"?: string;
        "onInputChange"?: (event: FieldInputCustomEvent<any>) => void;
        "pattern"?: string;
        "required"?: boolean;
        "type"?: string;
        "value"?: string;
    }
    interface FormInput {
        "label"?: string;
        "name"?: string;
        "onInputChange"?: (event: FormInputCustomEvent<any>) => void;
        "pattern"?: string;
        "required"?: boolean;
        "type"?: string;
        "value"?: string;
    }
    interface FormSelect {
        "label"?: string;
        "onFormSelectChange"?: (event: FormSelectCustomEvent<string>) => void;
        "options"?: string[];
        "required"?: boolean;
        "value"?: string;
    }
    interface PersonalDetails {
    }
    interface IntrinsicElements {
        "custom-select": CustomSelect;
        "field-input": FieldInput;
        "form-input": FormInput;
        "form-select": FormSelect;
        "personal-details": PersonalDetails;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-select": LocalJSX.CustomSelect & JSXBase.HTMLAttributes<HTMLCustomSelectElement>;
            "field-input": LocalJSX.FieldInput & JSXBase.HTMLAttributes<HTMLFieldInputElement>;
            "form-input": LocalJSX.FormInput & JSXBase.HTMLAttributes<HTMLFormInputElement>;
            "form-select": LocalJSX.FormSelect & JSXBase.HTMLAttributes<HTMLFormSelectElement>;
            "personal-details": LocalJSX.PersonalDetails & JSXBase.HTMLAttributes<HTMLPersonalDetailsElement>;
        }
    }
}
